---
title: "HW5"
author: "Bo"
date: "2026-03-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
data = read.csv("processed.csv", header = TRUE)

data = na.omit(data)


data$ca = as.factor(data$ca)
data$thal = as.factor(data$thal)

data$num = ifelse(data$num == 0, 0, 1)

head(data)
```


```{r}
# split dataset into training and testing
library(caTools)

# set up baseline regression: logistic regression. 
library(dplyr)

# random forest
library(randomForest)

# boosting algorithms, here gbm is used, there are other two boosting algorithms
library(gbm)
library(adabag)

# cross validation
library(caret)

# visualize a tree planted by random forest
#library(reprtree)
```


```{r pressure, echo=FALSE}
# splitting dataset
split = sample.split(data, SplitRatio = 0.8)
data.train = subset(data, split == "TRUE")
data.test = subset(data, split == "FALSE")
dim(data.train)
dim(data.test)
```


```{r}
#which(is.na(data))
#sum(is.na(data))
```


```{r}
logis = glm(as.factor(num)~age+sex+cp+trestbps+chol+fbs+restecg+thalach+exang+oldpeak+slope+ca+thal, data=data.train, family = "binomial")
logis
summary(logis)

logis.pred = predict(logis, data.test, type="response")
logis.pred = as.data.frame(logis.pred)

logis.pred = ifelse(logis.pred >= 0.5, 1, 0)
logis.confusion = confusionMatrix(as.factor(data.test$num), as.factor(logis.pred))

logis.accuracy = logis.confusion$overall[1]
logis.testingerror = 1-logis.accuracy

paste("Accuracy of Logistic Regression is :", logis.accuracy)
paste("Testing Error of Logistic Regression is :", logis.testingerror)


logis.two = glm(as.factor(num)~sex+cp+trestbps+fbs+thalach+exang+slope+ca, data=data.train, family = "binomial")
logis.two
```


```{r}

random = randomForest(as.factor(num)~age+sex+cp+trestbps+chol+fbs+restecg+thalach+exang+oldpeak+slope+ca+thal,data=data.train, importance=TRUE, mtry = 3, ntree=500)

summary(random)
#importance(random, type=1)
#importance(random, type=2)
varImpPlot(random)

random$confusion
training.accuracy = sum(diag(random$confusion))/sum(random$confusion)
paste("above is the accuracy of training dataset: ", training.accuracy)


random.pred = predict(random, data.test, type="class")

random.confusion = confusionMatrix(as.factor(random.pred), as.factor(data.test$num))
random.confusion


```


```{r}
# random forest with 5 folds cv
repeat_cv = trainControl(method='repeatedcv', number=5, repeats=3)

forest = train(as.factor(num)~age+sex+cp+trestbps+chol+fbs+restecg+thalach+exang+oldpeak+slope+ca+thal, data=data.train, method='rf', trControl=repeat_cv,metric='Accuracy')

forest.confusion = forest$finalModel$confusion

forest.accuracy = sum(diag(forest.confusion))/sum(forest.confusion)
forest.testingerror = 1-forest.accuracy

paste("Accuracy of random forest with 5 folds cv is: ", forest.accuracy)
paste("Testing Error of random forest with 5 folds cv is: ", forest.testingerror)

```







```{r}
boost = suppressWarnings(gbm(
  as.factor(num)~age+sex+cp+trestbps+chol+fbs+restecg+thalach+exang+oldpeak+slope+ca+thal, 
  data = data.train,
  distribution = "gaussian",
  cv.folds = 10,
  n.trees = 500,
  interaction.depth = 3,
  shrinkage = 0.1
))

summary(boost)

boost.pred = suppressWarnings(predict(boost, newdata = data.test))

boost.pred = as.factor(ifelse(boost.pred >=0.5, 1, 0))
data.test$num = as.factor(data.test$num)
boost.confusion = suppressWarnings(confusionMatrix(boost.pred, data.test$num))


boost.accuracy = boost.confusion$overall[1]
paste("Accuracy of boosting is: ", boost.accuracy)

boost.testingerror = 1-boost.accuracy
paste("Testing Error of boosting is: ", boost.testingerror)
```


```{r}

```







































