---
title: "DataMining--Project"
author: "Bo"
date: "2026-03-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
# split dataset into training and testing
library(caTools)
# set up baseline regression: logistic regression. 
library(dplyr)
# both packages are for multinomial logistic regression
library(VGAM)
# package for neural network algorithm
library(nnet)
# Splitting data into training and testing
library(caTools)
# package for random forest algorithm 
library(randomForest)
# package for adaboosting algorithm
library(adabag)
# package for cross validation
library(caret)
library(ggplot2)
#REF variable selection
library(caret)
# check correlation and plot it 
library(corrplot)
# for data manipulation
library(tidyverse)
# multicollinearity checking VIF
library(car)
# implement PCA. but since pca only work on numerical data, so we need another replacement that 
# can work on mixed datatype
library(FactoMineR)
library(factoextra)
# gradient boosting
library(gbm)
#for Durbin-Watson test to check autocorrelation among features.
library(lmtest)
# stacking model
library(h2o)
#checking auc score
library(pROC)

```


```{r}
numeric.data = read.csv("processed.csv", header = TRUE)
data = read.csv("processed.csv", header = TRUE)
```


```{r}
# Find column names where "?" exists
question.mark = names(data)[colSums(data == "?", na.rm = TRUE) > 0]
print(question.mark)
# to check ca and thal levels since there is special character in it. 
unique(data$ca)
unique(data$thal)
```

```{r}
# find out which row contains special characters
which(grepl("\\?", data$ca))
which(grepl("\\?", data$thal))
```

```{r}
removed.row = c(167, 193, 288, 303, 88, 267)
```


```{r}
numeric.data = numeric.data[-removed.row, ]
numeric.data$age = as.numeric(numeric.data$age)
numeric.data$sex = as.numeric(numeric.data$sex)
numeric.data$cp = as.numeric(numeric.data$cp)
numeric.data$trestbps = as.numeric(numeric.data$trestbps)
numeric.data$chol = as.numeric(numeric.data$chol)
numeric.data$fbs = as.numeric(numeric.data$fbs)
numeric.data$restecg = as.numeric(numeric.data$restecg)
numeric.data$thalach = as.numeric(numeric.data$thalach)
numeric.data$exang = as.numeric(numeric.data$exang)
numeric.data$oldpeak = as.numeric(numeric.data$oldpeak)
numeric.data$slope = as.numeric(numeric.data$slope)
numeric.data$ca = as.numeric(numeric.data$ca)
numeric.data$thal = as.numeric(numeric.data$thal)
numeric.data$num = ifelse(numeric.data$num == 0, 0, 1)
numeric.data$num = as.numeric(numeric.data$num)
```


```{r}
correlations=cor(numeric.data[,-14])
corrplot(correlations, method="number", number.cex= 8/ncol(numeric.data))

```


```{r pressure, echo=FALSE}
data$num = ifelse(data$num == 0, 0, 1)
data$ca = as.factor(data$ca)
data$thal = as.factor(data$thal)
data$num = as.factor(data$num)
data$sex = as.factor(data$sex)
data$cp = as.factor(data$cp)
data$fbs = as.factor(data$fbs)
data$restecg = as.factor(data$restecg)
data$fbs = as.factor(data$fbs)
data$exang = as.factor(data$exang)
data$slope = as.factor(data$slope)
```


```{r}
plot(data$trestbps, data$num, xlab="trestbps", ylab="num")
lines(smooth.spline(data$num~data$trestbps, df=4))
```



```{r}
plot(data$chol, data$num, xlab="chol", ylab="num")
lines(smooth.spline(data$num~data$chol, df=4))
```


```{r}
plot(data$thalach, data$num, xlab="thalach", ylab="num")
lines(smooth.spline(data$num~data$thalach, df=5))
```



```{r}
plot(data$oldpeak, data$num, xlab="oldpeak", ylab="num")
lines(smooth.spline(data$num~data$oldpeak, df=5))
```


```{r}
file = data[-removed.row, ]
dim(file)
```


```{r}
# since the unit of each column is different, they need a normalization.
normalization = function(x){
  z = (x-mean(x))/(sd(x))
}
```



```{r}
file[, c("age", "trestbps", "chol", "thalach", "oldpeak")] = as.data.frame(lapply(file[, c("age", "trestbps", "chol", "thalach", "oldpeak")], normalization))
```


```{r}
# in this spliting method, dataset can be split into three parts, train, test, validation, but i only split into two datasets. 
split.dataset = c(train = .8, test = .2)

proportion = sample(
  cut(seq(nrow(file)), nrow(file)*cumsum(c(0,split.dataset)),labels = names(split.dataset))
)

train.test = split(file, proportion)
```

```{r}
train = as.data.frame(train.test$train)
dim(train)

test = as.data.frame(train.test$test)
dim(test)

```


```{r}
train %>% ggplot(aes(num)) + geom_bar() + labs(x="Num", y="Absolute Frequency")
```


```{r}
#multinomial logistic regression using vgam package
logistic = glm(num~age+sex+cp+trestbps+chol+I(chol^2)+fbs+restecg+thalach+exang+oldpeak+slope+I(oldpeak^2)+ca+thal, data=train, family = "binomial")
#summary(logistic)
logistic.pred = predict(logistic, newdata=test, type="response")
logis.pred = ifelse(logistic.pred >= 0.5, 1, 0)
logis.confusion = confusionMatrix(test$num, as.factor(logis.pred))
logis.accuracy = logis.confusion$overall[1]
logis.accuracy
```

```{r}
# Multicollinearity checking, here need to use car:: even car is loaded by library()
vif.result = car::vif(logistic)
vif.result
```


```{r}
# FAMD is same like pca,but famd can work on mixed datatype, pca only works on numerical data
famd = FAMD(train, sup.var = 14, graph= FALSE, ncp=25)
get_eigenvalue(famd)
```


```{r}
# check outliers
cooks.distance(logistic)[which.max(cooks.distance(logistic))]
```


```{r}
plot(logistic, which = 4)
```


```{r}
#checking autocorrelation among features 
dw.test = dwtest(logistic)
dw.test
```


```{r}
random = randomForest(num~.,data=train, importance=TRUE, mtry = 10, ntree=500)
varImpPlot(random)
random.pred = predict(random, test, type="class")
random.confusion = confusionMatrix(as.factor(random.pred), test$num)
random.confusion
```


```{r}
# random forest with 10 folds cv
repeat_cv = trainControl(method='repeatedcv', number=10, repeats=3)
tenfold.forest = train(num~., data=train, method='rf', trControl=repeat_cv, metric='Accuracy')
tenfold.forest.pred = predict(tenfold.forest, newdata=test)
forest.confusion = table(tenfold.forest.pred, test$num )
forest.accuracy = sum(diag(forest.confusion))/sum(forest.confusion)
forest.accuracy
```


```{r}
# gradient boosting 
gra.boost = boosting(num~., data = train, mfinal = 10, boos = TRUE)
gra.pred = predict(gra.boost, newdata= test)
gra.confusion= table(gra.pred$class, test$num)
gra.accuracy = sum(diag(gra.confusion)) / sum(gra.confusion)
gra.accuracy
```


```{r}
# Specify RFE control parameters with random forest function
forest.ctrl = suppressWarnings(rfeControl(functions = rfFuncs, method = "cv", number = 10) ) 
# Perform RFE
forest.rfe = suppressWarnings(rfe(file[, -14], file[, 14], sizes = c(1:13), rfeControl = forest.ctrl) ) 
# Print RFE results
print(forest.rfe)
```


```{r}
random.two = randomForest(num~ca+thal+cp+oldpeak+sex,data=train, importance=TRUE, mtry = 10, ntree=500)
varImpPlot(random.two)
random.pred.two = predict(random.two, test, type="class")
random.confusion.two = confusionMatrix(as.factor(random.pred.two), test$num)
random.confusion.two
```


```{r}
rf.auc = auc(test$num, as.numeric(random.pred.two))
rf.auc
```


```{r}
train$chol2 = (train$chol)^2
train$oldpeak2 = (train$oldpeak)^2
colnames(train)
```


```{r}
# Specify RFE control parameters with logistic regression function
logistic.ctrl = suppressWarnings(rfeControl(functions = lrFuncs, method = "cv", number = 10) ) 

# Perform RFE
logistic.rfe = suppressWarnings(rfe(num~age+sex+cp+trestbps+chol+chol2+fbs+restecg+thalach+exang+oldpeak+slope+oldpeak2+ca+thal, data=train, sizes = c(1:14), rfeControl=logistic.ctrl) )

# Print RFE results
print(logistic.rfe)
```


```{r}
# logistc after RFE
logistic.three = glm(num~thal+slope+ca+sex, data=train, family = "binomial")
summary(logistic.three)
logistic.pred.three = predict(logistic.three, newdata=test, type="response")
logis.pred.three = ifelse(logistic.pred.three >= 0.5, 1, 0)
logis.confusion.three = confusionMatrix(test$num, as.factor(logis.pred.three))
logis.accuracy.three = logis.confusion$overall[1]
logis.accuracy.three
```


```{r}
log.auc = auc(test$num, logis.pred.three)
log.auc
```


```{r}
car::vif(logistic.three)
```


```{r}
# Specify RFE control parameters with bagged  trees function
treebag.ctrl = suppressWarnings(rfeControl(functions = treebagFuncs, method = "cv", number = 10) ) 

# Perform RFE
treebag.rfe = suppressWarnings(rfe(train[, -14], train[, 14], sizes = c(1:13), rfeControl = treebag.ctrl) ) 

# Print RFE results
print(treebag.rfe)
```


```{r}
repeat_cv = trainControl(method='repeatedcv', number=10, repeats=3)

tenfold.forest.two = train(num~+ca+cp+thal+oldpeak, data=train, method='rf', trControl=repeat_cv, metric='Accuracy')

tenfold.forest.pred.two = predict(tenfold.forest.two, newdata=test)

forest.confusion.two = table(tenfold.forest.pred.two, test$num )

forest.accuracy.two = sum(diag(forest.confusion.two))/sum(forest.confusion.two)
forest.accuracy.two
```


```{r}
# gradient boosting 
gra.boost.two = boosting(num~ca+cp+thal+oldpeak, data = train, mfinal = 10, boos = TRUE)
gra.pred.two = predict(gra.boost.two, newdata= test)

gra.confusion.two= table(gra.pred.two$class, test$num)
gra.accuracy.two = sum(diag(gra.confusion.two)) / sum(gra.confusion.two)
gra.accuracy.two
```


```{r}
gra.auc = auc(test$num, as.numeric(gra.pred.two$class))
gra.auc
```


```{r}
# stacking models
h2o.init()
```


```{r}
train.h2o=as.h2o(train)
test.h2o=as.h2o(test)
```
```{r}
#setting up dependent variable and independent variables
y = "num"
x = setdiff(names(train.h2o), y)
x
```

```{r}
#setting up cross validation folds to generate level one data for stacking
fold = 10
```


```{r}
# generate a gbm 
gbm.features = c("ca","cp","thal","oldpeak")  
gbm = h2o.gbm(
  x=gbm.features, 
  y=y, 
  training_frame=train.h2o, 
  nfolds=fold, 
  keep_cross_validation_predictions=TRUE, 
  seed = 5
  )
```


```{r}
# generate a random forest
rf.features = c("sex", "ca","cp","thal","oldpeak")
rf = h2o.randomForest(
  x = rf.features,
  y = y,
  training_frame = train.h2o,
  nfolds = fold,
  keep_cross_validation_predictions = TRUE,
  seed = 5
  )
```


```{r}
# generate a Logistic Regression
log.features = c("thal","slope","ca","sex", "exang" ) 
lr = h2o.glm(x = log.features,
             y = y,
             training_frame = train.h2o,
             family = c("binomial"),
             nfolds = fold,
             keep_cross_validation_predictions = TRUE,
             seed = 5)
```


```{r}
# Train a stacked random forest ensemble using gradient boosting, random forest and logistic regression 
ensemble = h2o.stackedEnsemble(x = x,
                                y = y,
                                metalearner_algorithm="drf",
                                training_frame = train.h2o,
                                base_models = list(gbm, rf, lr))
```


```{r}
# Eval ensemble performance on a test set
performance = h2o.performance(ensemble, newdata = test.h2o)

```


```{r}
# Compare to base learner performance on the test set
performance.gbm = h2o.performance(gbm, newdata = test.h2o)
performance.rf = h2o.performance(rf, newdata = test.h2o)
perfformance.lr = h2o.performance(lr, newdata = test.h2o)
baselearner.best.auc = max(h2o.auc(performance.gbm), h2o.auc(performance.rf), h2o.auc(perfformance.lr))
ensemble.auc = h2o.auc(performance)
print(sprintf("Best Base learner Test AUC:  %s", baselearner.best.auc))
print(sprintf("Ensemble Test AUC:  %s", ensemble.auc))
```

```{r}
auc.test = as.data.frame(rbind(
  gbm.auc = h2o.auc(performance.gbm), 
  rf.auc = h2o.auc(performance.rf), 
  lr.auc = h2o.auc(perfformance.lr), 
  emsemble.auc = ensemble.auc))
auc.test
```






















































